# Generated by Django 5.1.7 on 2025-04-07 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('category', models.CharField(choices=[('account', 'Account'), ('billing', 'Billing'), ('technical', 'Technical'), ('general', 'General')], default='general', max_length=50)),
            ],
        ),
    ]
