# Generated by Django 5.1.7 on 2025-04-07 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='testimonials/')),
                ('comment', models.TextField()),
            ],
        ),
    ]
