# Generated by Django 5.1.7 on 2025-04-07 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentpage', '0002_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('need_type', models.CharField(choices=[('management', 'Property Management'), ('maintenance', 'Maintenance'), ('rental', 'Rental Inquiry'), ('other', 'Other')], max_length=50)),
                ('message', models.TextField()),
            ],
        ),
    ]
