# Generated by Django 5.1.7 on 2025-08-13 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentpage', '0003_usermessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='category',
            field=models.CharField(choices=[('account', 'Account'), ('billing', 'Billing'), ('technical', 'Technical'), ('general', 'General'), ('services', 'Services'), ('membership', 'Membership')], default='general', max_length=50),
        ),
    ]
