# Generated by Django 5.1.7 on 2025-04-02 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertydetails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertymanagement',
            name='floor_plans',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
