# Generated by Django 5.1.7 on 2025-04-02 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertydetails', '0002_propertymanagement_floor_plans'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertymanagement',
            name='floor_plans',
        ),
        migrations.AddField(
            model_name='propertymanagement',
            name='floor_plan_10_image',
            field=models.ImageField(blank=True, null=True, upload_to='floor_plans/'),
        ),
        migrations.AddField(
            model_name='propertymanagement',
            name='floor_plan_10_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='propertymanagement',
            name='floor_plan_1_image',
            field=models.ImageField(blank=True, null=True, upload_to='floor_plans/'),
        ),
        migrations.AddField(
            model_name='propertymanagement',
            name='floor_plan_1_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='propertymanagement',
            name='floor_plan_2_image',
            field=models.ImageField(blank=True, null=True, upload_to='floor_plans/'),
        ),
        migrations.AddField(
            model_name='propertymanagement',
            name='floor_plan_2_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='propertymanagement',
            name='floor_plan_3_image',
            field=models.ImageField(blank=True, null=True, upload_to='floor_plans/'),
        ),
        migrations.AddField(
            model_name='propertymanagement',
            name='floor_plan_3_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='propertymanagement',
            name='floor_plan_4_image',
            field=models.ImageField(blank=True, null=True, upload_to='floor_plans/'),
        ),
        migrations.AddField(
            model_name='propertymanagement',
            name='floor_plan_4_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='propertymanagement',
            name='floor_plan_5_image',
            field=models.ImageField(blank=True, null=True, upload_to='floor_plans/'),
        ),
        migrations.AddField(
            model_name='propertymanagement',
            name='floor_plan_5_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='propertymanagement',
            name='floor_plan_6_image',
            field=models.ImageField(blank=True, null=True, upload_to='floor_plans/'),
        ),
        migrations.AddField(
            model_name='propertymanagement',
            name='floor_plan_6_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='propertymanagement',
            name='floor_plan_7_image',
            field=models.ImageField(blank=True, null=True, upload_to='floor_plans/'),
        ),
        migrations.AddField(
            model_name='propertymanagement',
            name='floor_plan_7_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='propertymanagement',
            name='floor_plan_8_image',
            field=models.ImageField(blank=True, null=True, upload_to='floor_plans/'),
        ),
        migrations.AddField(
            model_name='propertymanagement',
            name='floor_plan_8_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='propertymanagement',
            name='floor_plan_9_image',
            field=models.ImageField(blank=True, null=True, upload_to='floor_plans/'),
        ),
        migrations.AddField(
            model_name='propertymanagement',
            name='floor_plan_9_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
