# Generated by Django 5.1.7 on 2025-04-02 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertydetails', '0003_remove_propertymanagement_floor_plans_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertymanagement',
            name='floor_plan_10_image',
        ),
        migrations.RemoveField(
            model_name='propertymanagement',
            name='floor_plan_10_name',
        ),
        migrations.RemoveField(
            model_name='propertymanagement',
            name='floor_plan_1_image',
        ),
        migrations.RemoveField(
            model_name='propertymanagement',
            name='floor_plan_2_image',
        ),
        migrations.RemoveField(
            model_name='propertymanagement',
            name='floor_plan_3_image',
        ),
        migrations.RemoveField(
            model_name='propertymanagement',
            name='floor_plan_4_image',
        ),
        migrations.RemoveField(
            model_name='propertymanagement',
            name='floor_plan_5_image',
        ),
        migrations.RemoveField(
            model_name='propertymanagement',
            name='floor_plan_5_name',
        ),
        migrations.RemoveField(
            model_name='propertymanagement',
            name='floor_plan_6_image',
        ),
        migrations.RemoveField(
            model_name='propertymanagement',
            name='floor_plan_6_name',
        ),
        migrations.RemoveField(
            model_name='propertymanagement',
            name='floor_plan_7_image',
        ),
        migrations.RemoveField(
            model_name='propertymanagement',
            name='floor_plan_7_name',
        ),
        migrations.RemoveField(
            model_name='propertymanagement',
            name='floor_plan_8_image',
        ),
        migrations.RemoveField(
            model_name='propertymanagement',
            name='floor_plan_8_name',
        ),
        migrations.RemoveField(
            model_name='propertymanagement',
            name='floor_plan_9_image',
        ),
        migrations.RemoveField(
            model_name='propertymanagement',
            name='floor_plan_9_name',
        ),
        migrations.AddField(
            model_name='propertymanagement',
            name='floor_plan_1_file',
            field=models.FileField(blank=True, null=True, upload_to='floor_plans/'),
        ),
        migrations.AddField(
            model_name='propertymanagement',
            name='floor_plan_2_file',
            field=models.FileField(blank=True, null=True, upload_to='floor_plans/'),
        ),
        migrations.AddField(
            model_name='propertymanagement',
            name='floor_plan_3_file',
            field=models.FileField(blank=True, null=True, upload_to='floor_plans/'),
        ),
        migrations.AddField(
            model_name='propertymanagement',
            name='floor_plan_4_file',
            field=models.FileField(blank=True, null=True, upload_to='floor_plans/'),
        ),
        migrations.AlterField(
            model_name='propertymanagement',
            name='floor_plan_1_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='propertymanagement',
            name='floor_plan_2_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='propertymanagement',
            name='floor_plan_3_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='propertymanagement',
            name='floor_plan_4_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
