# Generated by Django 5.1.7 on 2025-04-02 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propertydetails', '0005_vendor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
