# Generated by Django 5.1.7 on 2025-04-03 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertydetails', '0007_propertyimprovement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyimprovement',
            name='client_approval',
            field=models.CharField(choices=[('pending', 'Pending'), ('yes', 'Yes'), ('no', 'No')], default='pending', max_length=7),
        ),
    ]
