# Generated by Django 5.1.7 on 2025-04-04 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertydetails', '0008_alter_propertyimprovement_client_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyimprovement',
            name='client_approval',
            field=models.CharField(choices=[('pending', 'Pending'), ('Approved', 'Approved'), ('Deny', 'Deny')], default='pending', max_length=20),
        ),
    ]
