# Generated by Django 5.1.7 on 2025-04-06 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_vendor_service'),
        ('propertydetails', '0009_alter_propertyimprovement_client_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyimprovement',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.vendor'),
        ),
    ]
