# Generated by Django 5.1.7 on 2025-04-13 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertydetails', '0010_propertyimprovement_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertymanagement',
            name='floor_plan_1_file',
        ),
        migrations.RemoveField(
            model_name='propertymanagement',
            name='floor_plan_1_name',
        ),
        migrations.RemoveField(
            model_name='propertymanagement',
            name='floor_plan_2_file',
        ),
        migrations.RemoveField(
            model_name='propertymanagement',
            name='floor_plan_2_name',
        ),
        migrations.RemoveField(
            model_name='propertymanagement',
            name='floor_plan_3_file',
        ),
        migrations.RemoveField(
            model_name='propertymanagement',
            name='floor_plan_3_name',
        ),
        migrations.RemoveField(
            model_name='propertymanagement',
            name='floor_plan_4_file',
        ),
        migrations.RemoveField(
            model_name='propertymanagement',
            name='floor_plan_4_name',
        ),
        migrations.CreateModel(
            name='FloorPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('plan_file', models.FileField(blank=True, null=True, upload_to='floor_plans/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floor_plans', to='propertydetails.propertymanagement')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='room_images/')),
                ('floor_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='propertydetails.floorplan')),
            ],
        ),
    ]
