# Generated by Django 5.1.7 on 2025-04-13 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertydetails', '0011_remove_propertymanagement_floor_plan_1_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='floor_plan',
        ),
        migrations.RemoveField(
            model_name='room',
            name='image',
        ),
        migrations.RemoveField(
            model_name='room',
            name='name',
        ),
        migrations.AddField(
            model_name='room',
            name='room_image',
            field=models.ImageField(blank=True, null=True, upload_to='rooms_images/'),
        ),
        migrations.AddField(
            model_name='room',
            name='room_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='room_size',
            field=models.CharField(default=4, max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_name', models.CharField(max_length=255)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='propertydetails.propertymanagement')),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='floor',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='propertydetails.floor'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='FloorPlan',
        ),
    ]
