# Generated by Django 5.1.7 on 2025-04-16 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertydetails', '0012_remove_room_floor_plan_remove_room_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertymanagement',
            name='city',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='propertymanagement',
            name='state',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
