# Generated by Django 5.1.7 on 2025-04-26 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertydetails', '0013_propertymanagement_city_propertymanagement_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='floor',
            name='floor_imgae',
            field=models.ImageField(blank=True, null=True, upload_to='floor_images/'),
        ),
    ]
