# Generated by Django 5.1.7 on 2025-05-08 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertydetails', '0014_floor_floor_imgae'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertymanagement',
            name='zipcode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
