# Generated by Django 5.1.7 on 2025-07-07 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertydetails', '0015_propertymanagement_zipcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertymanagement',
            name='basketball_court',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propertymanagement',
            name='hot_tub',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propertymanagement',
            name='outdoor_kitchen_gazebo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propertymanagement',
            name='pickleball_court',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propertymanagement',
            name='tennis_court',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propertymanagement',
            name='waterfront',
            field=models.BooleanField(default=False),
        ),
    ]
