# Generated by Django 5.1.7 on 2025-07-07 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertydetails', '0016_propertymanagement_basketball_court_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertymanagement',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
