# Generated by Django 5.1.7 on 2025-07-18 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertydetails', '0017_propertymanagement_additional_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertymanagement',
            name='street_line1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='propertymanagement',
            name='street_line2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
