# Generated by Django 5.1.7 on 2025-09-06 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertydetails', '0018_propertymanagement_street_line1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertymanagement',
            name='property_pic',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/'),
        ),
    ]
