# Generated by Django 5.1.7 on 2025-09-13 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertydetails', '0019_propertymanagement_property_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floor',
            name='floor_imgae',
            field=models.FileField(blank=True, null=True, upload_to='floor_files/'),
        ),
    ]
