# Generated by Django 5.1.7 on 2025-04-02 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicedetails', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='title',
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='request_type',
            field=models.CharField(choices=[('interior_residence', 'INTERIOR RESIDENCE'), ('exterior_structure', 'EXTERIOR STRUCTURE'), ('exterior_grounds', 'EXTERIOR GROUNDS'), ('housekeeping', 'HOUSEKEEPING'), ('water_features', 'WATER FEATURES'), ('storm_preparedness', 'STORM PREPAREDNESS'), ('other', 'OTHER')], default=5, max_length=50),
            preserve_default=False,
        ),
    ]
