# Generated by Django 5.1.7 on 2025-04-03 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_vendor'),
        ('servicedetails', '0003_userpreferences'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserPreferences',
            new_name='PrearrivalInformation',
        ),
    ]
