# Generated by Django 5.1.7 on 2025-04-03 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_vendor'),
        ('servicedetails', '0004_rename_userpreferences_prearrivalinformation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prearrivalinformation',
            name='additional',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prearrivalinformation',
            name='alcohol',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prearrivalinformation',
            name='arrival_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prearrivalinformation',
            name='arrival_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prearrivalinformation',
            name='automobiles',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prearrivalinformation',
            name='flower_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='prearrivalinformation',
            name='flower_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='prearrivalinformation',
            name='groceries_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prearrivalinformation',
            name='hot_bath_temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prearrivalinformation',
            name='housekeeping',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prearrivalinformation',
            name='indoor_lights',
            field=models.CharField(blank=True, choices=[('all_on', 'All On'), ('all_off', 'All Off')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='prearrivalinformation',
            name='music_genre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='prearrivalinformation',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='prearrivalinformation',
            name='outdoor_lights',
            field=models.CharField(blank=True, choices=[('all_on', 'All On'), ('all_off', 'All Off')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='prearrivalinformation',
            name='pool_temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prearrivalinformation',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prearrivalinformation',
            name='transportation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prearrivalinformation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.client'),
        ),
        migrations.AlterField(
            model_name='prearrivalinformation',
            name='window_position',
            field=models.CharField(blank=True, choices=[('up', 'Up'), ('down', 'Down'), ('sideway', 'Sideway')], max_length=10, null=True),
        ),
    ]
