# Generated by Django 5.1.7 on 2025-04-03 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_vendor'),
        ('servicedetails', '0005_alter_prearrivalinformation_additional_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartureInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('departure_date', models.DateField(blank=True, null=True)),
                ('departure_time', models.TimeField(blank=True, null=True)),
                ('housekeeping', models.TextField(blank=True, null=True)),
                ('wash', models.TextField(blank=True, null=True)),
                ('trash', models.TextField(blank=True, null=True)),
                ('additional', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.client')),
            ],
        ),
    ]
