# Generated by Django 5.1.7 on 2025-04-13 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicedetails', '0007_conciergeservicerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='floor_plan_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
