# Generated by Django 5.1.7 on 2025-04-20 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicedetails', '0008_servicerequest_floor_plan_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='departureinformation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('open', 'Open'), ('completed', 'Completed'), ('denied', 'Denied')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='prearrivalinformation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('open', 'Open'), ('completed', 'Completed'), ('denied', 'Denied')], default='pending', max_length=10),
        ),
    ]
