# Generated by Django 5.1.7 on 2025-06-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicedetails', '0010_alter_servicerequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conciergeservicerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('open', 'Open'), ('completed', 'Completed'), ('denied', 'Denied')], default='open', max_length=10),
        ),
    ]
