# Generated by Django 5.1.7 on 2025-06-25 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicedetails', '0011_alter_conciergeservicerequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='conciergeservicerequest',
            name='completation_denied_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='completation_denied_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
