# Generated by Django 5.1.7 on 2025-06-28 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicedetails', '0012_conciergeservicerequest_completation_denied_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departureinformation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('open', 'Open'), ('completed', 'Completed'), ('denied', 'Denied')], default='open', max_length=10),
        ),
        migrations.AlterField(
            model_name='prearrivalinformation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('open', 'Open'), ('completed', 'Completed'), ('denied', 'Denied')], default='open', max_length=10),
        ),
    ]
