# Generated by Django 5.1.7 on 2025-07-09 14:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicedetails', '0013_alter_departureinformation_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prearrivalinformation',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
