# Generated by Django 5.1.7 on 2025-07-09 14:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicedetails', '0014_prearrivalinformation_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='departureinformation',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
