# Generated by Django 5.1.7 on 2025-07-09 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicedetails', '0015_departureinformation_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
