# Generated by Django 5.1.7 on 2025-07-09 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicedetails', '0016_servicerequest_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='cost',
            field=models.IntegerField(default=0),
        ),
    ]
