# Generated by Django 5.1.7 on 2025-08-06 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicedetails', '0018_conciergeservicerequest_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='client_approval',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Denied', 'Denied')], default='Pending', max_length=10),
        ),
    ]
