# Generated by Django 5.1.7 on 2025-08-06 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicedetails', '0019_servicerequest_client_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='cost_remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
