# Generated by Django 5.1.7 on 2025-08-06 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicedetails', '0020_servicerequest_cost_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='status_remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
