# Generated by Django 5.1.7 on 2025-08-06 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicedetails', '0021_servicerequest_status_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='conciergeservicerequest',
            name='client_approval',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Denied', 'Denied')], default='Pending', max_length=10),
        ),
        migrations.AddField(
            model_name='conciergeservicerequest',
            name='cost_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conciergeservicerequest',
            name='floor_plan_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='conciergeservicerequest',
            name='status_remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
