# Generated by Django 5.1.7 on 2025-08-12 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicedetails', '0022_conciergeservicerequest_client_approval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prearrivalinformation',
            name='client_approval',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Denied', 'Denied')], default='Pending', max_length=10),
        ),
        migrations.AddField(
            model_name='prearrivalinformation',
            name='cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='prearrivalinformation',
            name='cost_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prearrivalinformation',
            name='status_remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
