# Generated by Django 5.1.7 on 2025-08-13 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicedetails', '0023_prearrivalinformation_client_approval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prearrivalinformation',
            name='completation_denied_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
