# Generated by Django 5.1.7 on 2025-08-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicedetails', '0024_prearrivalinformation_completation_denied_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='departureinformation',
            name='client_approval',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Denied', 'Denied')], default='Pending', max_length=10),
        ),
        migrations.AddField(
            model_name='departureinformation',
            name='completation_denied_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='departureinformation',
            name='cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='departureinformation',
            name='cost_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='departureinformation',
            name='status_remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
