# Generated by Django 5.1.7 on 2025-04-09 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminmanager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_provider', models.CharField(choices=[('twilio', 'Twilio'), ('plivo', 'Plivo'), ('nexmo', 'Nexmo'), ('custom', 'Custom')], default='twilio', max_length=50)),
                ('account_sid', models.CharField(blank=True, max_length=255, null=True)),
                ('auth_token', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, help_text='Registered calling number', max_length=20, null=True)),
                ('webhook_url', models.URLField(blank=True, help_text='URL to receive call events', null=True)),
                ('use_voice_call', models.BooleanField(default=True)),
                ('use_sms', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MailConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_host', models.CharField(blank=True, max_length=255, null=True)),
                ('email_port', models.PositiveIntegerField(blank=True, null=True)),
                ('email_host_user', models.EmailField(blank=True, max_length=254, null=True)),
                ('email_host_password', models.CharField(blank=True, max_length=255, null=True)),
                ('use_tls', models.BooleanField(default=True)),
                ('use_ssl', models.BooleanField(default=False)),
                ('default_from_email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
