# Generated by Django 5.1.7 on 2025-07-26 18:48

import django.db.models.deletion
import walkthroughreport.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainapp', '0023_alter_client_password_alter_client_username'),
        ('propertydetails', '0018_propertymanagement_street_line1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalkthroughReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('updatedate', models.DateField(blank=True, null=True)),
                ('datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('cost', models.IntegerField(blank=True, default=0, null=True)),
                ('cost_notes', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Open', 'Open'), ('Completed', 'Completed'), ('Denied', 'Denied')], default='Open', max_length=20, null=True)),
                ('item_status_check', models.BooleanField(default=False)),
                ('status_remarks', models.CharField(blank=True, max_length=500, null=True)),
                ('client_approval', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Denied', 'Denied')], default='Pending', max_length=10)),
                ('completation_denied_date', models.DateField(blank=True, null=True)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='propertydetails.propertymanagement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.client')),
            ],
        ),
        migrations.CreateModel(
            name='TheatreMusicRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('walkthrough_report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='theatre_music_room', to='walkthroughreport.walkthroughreport')),
            ],
        ),
        migrations.CreateModel(
            name='Laundry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('walkthrough_report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='laundry', to='walkthroughreport.walkthroughreport')),
            ],
        ),
        migrations.CreateModel(
            name='Kitchen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('walkthrough_report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kitchen', to='walkthroughreport.walkthroughreport')),
            ],
        ),
        migrations.CreateModel(
            name='HallwaysUpperLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('walkthrough_report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hallways_upper_level', to='walkthroughreport.walkthroughreport')),
            ],
        ),
        migrations.CreateModel(
            name='HallwaysMainLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('walkthrough_report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hallways_main_level', to='walkthroughreport.walkthroughreport')),
            ],
        ),
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('walkthrough_report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gym', to='walkthroughreport.walkthroughreport')),
            ],
        ),
        migrations.CreateModel(
            name='GuestHouseSleepingLiving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('walkthrough_report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guest_house_sleeping_living', to='walkthroughreport.walkthroughreport')),
            ],
        ),
        migrations.CreateModel(
            name='GreatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('walkthrough_report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='great_room', to='walkthroughreport.walkthroughreport')),
            ],
        ),
        migrations.CreateModel(
            name='GeneralItemsInterior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gii1', walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Visual Inspection: Interior of House')),
                ('gii1_remarks', models.CharField(blank=True, max_length=500, null=True)),
                ('gii2', walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Exterior Doors Codes')),
                ('gii2_remarks', models.CharField(blank=True, max_length=500, null=True)),
                ('gii3', walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Exterior Doors & Hardware')),
                ('gii3_remarks', models.CharField(blank=True, max_length=500, null=True)),
                ('gii4', walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Exterior Windows & Hardware')),
                ('gii4_remarks', models.CharField(blank=True, max_length=500, null=True)),
                ('gii5', walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Smoke Detectors')),
                ('gii5_remarks', models.CharField(blank=True, max_length=500, null=True)),
                ('gii6', walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='A/C Air Handling Unit #1')),
                ('gii6_remarks', models.CharField(blank=True, max_length=500, null=True)),
                ('gii7', walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='A/C Air Handling Unit #2')),
                ('gii7_remarks', models.CharField(blank=True, max_length=500, null=True)),
                ('gii8', walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='A/C Air Handling Unit #3')),
                ('gii8_remarks', models.CharField(blank=True, max_length=500, null=True)),
                ('gii9', walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='A/C Air Handling Unit #4')),
                ('gii9_remarks', models.CharField(blank=True, max_length=500, null=True)),
                ('gii10', walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='A/C Air Handling Unit #5')),
                ('gii10_remarks', models.CharField(blank=True, max_length=500, null=True)),
                ('walkthrough_report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='general_items_interior', to='walkthroughreport.walkthroughreport')),
            ],
        ),
        migrations.CreateModel(
            name='GeneralItemsExterior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gie1', walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Visual Inspection: Exterior of House')),
                ('gie1_remarks', models.CharField(blank=True, max_length=500, null=True)),
                ('gie2', walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Drives / Walkways')),
                ('gie2_remarks', models.CharField(blank=True, max_length=500, null=True)),
                ('gie3', walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Generator: Reading Operational')),
                ('gie3_remarks', models.CharField(blank=True, max_length=500, null=True)),
                ('gie4', walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Irrigation: Zones & Heads Tested')),
                ('gie4_remarks', models.CharField(blank=True, max_length=500, null=True)),
                ('gie5', walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Propane Tank Meter Read')),
                ('gie5_remarks', models.CharField(blank=True, max_length=500, null=True)),
                ('gie6', walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='A/C Air Handling Unit #1')),
                ('gie6_remarks', models.CharField(blank=True, max_length=500, null=True)),
                ('gie7', walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='A/C Air Handling Unit #2')),
                ('gie7_remarks', models.CharField(blank=True, max_length=500, null=True)),
                ('gie8', walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='A/C Air Handling Unit #3')),
                ('gie8_remarks', models.CharField(blank=True, max_length=500, null=True)),
                ('gie9', walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='A/C Air Handling Unit #4')),
                ('gie9_remarks', models.CharField(blank=True, max_length=500, null=True)),
                ('gie10', walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='A/C Air Handling Unit #5')),
                ('gie10_remarks', models.CharField(blank=True, max_length=500, null=True)),
                ('gie11', walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Mail')),
                ('gie11_remarks', models.CharField(blank=True, max_length=500, null=True)),
                ('gie12', walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Outdoor Furniture')),
                ('gie12_remarks', models.CharField(blank=True, max_length=500, null=True)),
                ('gie13', walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Roof Eaves, Fascias, Gutters')),
                ('gie13_remarks', models.CharField(blank=True, max_length=500, null=True)),
                ('gie14', walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Exterior Lights (Sconces, Flood)')),
                ('gie14_remarks', models.CharField(blank=True, max_length=500, null=True)),
                ('gie15', walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Mailbox')),
                ('gie15_remarks', models.CharField(blank=True, max_length=500, null=True)),
                ('walkthrough_report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='general_items_exterior', to='walkthroughreport.walkthroughreport')),
            ],
        ),
        migrations.CreateModel(
            name='Garage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('walkthrough_report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='garage', to='walkthroughreport.walkthroughreport')),
            ],
        ),
        migrations.CreateModel(
            name='EntryFoyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('walkthrough_report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entry_foyer', to='walkthroughreport.walkthroughreport')),
            ],
        ),
        migrations.CreateModel(
            name='DiningRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('walkthrough_report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dining_room', to='walkthroughreport.walkthroughreport')),
            ],
        ),
        migrations.CreateModel(
            name='ClosetsUpperLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('walkthrough_report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='closets_upper_level', to='walkthroughreport.walkthroughreport')),
            ],
        ),
        migrations.CreateModel(
            name='ClosetsMainLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('walkthrough_report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='closets_main_level', to='walkthroughreport.walkthroughreport')),
            ],
        ),
        migrations.CreateModel(
            name='Butlers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('walkthrough_report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='butlers', to='walkthroughreport.walkthroughreport')),
            ],
        ),
        migrations.CreateModel(
            name='BreakfastArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('walkthrough_report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='breakfast_area', to='walkthroughreport.walkthroughreport')),
            ],
        ),
        migrations.CreateModel(
            name='Bedroom9',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('walkthrough_report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bedroom9', to='walkthroughreport.walkthroughreport')),
            ],
        ),
        migrations.CreateModel(
            name='Bedroom8',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('walkthrough_report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bedroom8', to='walkthroughreport.walkthroughreport')),
            ],
        ),
        migrations.CreateModel(
            name='Bedroom7',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('walkthrough_report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bedroom7', to='walkthroughreport.walkthroughreport')),
            ],
        ),
        migrations.CreateModel(
            name='Bedroom6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('walkthrough_report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bedroom6', to='walkthroughreport.walkthroughreport')),
            ],
        ),
        migrations.CreateModel(
            name='Bedroom5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('walkthrough_report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bedroom5', to='walkthroughreport.walkthroughreport')),
            ],
        ),
        migrations.CreateModel(
            name='Bedroom4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('walkthrough_report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bedroom4', to='walkthroughreport.walkthroughreport')),
            ],
        ),
        migrations.CreateModel(
            name='Bedroom3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('walkthrough_report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bedroom3', to='walkthroughreport.walkthroughreport')),
            ],
        ),
        migrations.CreateModel(
            name='Bedroom2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('walkthrough_report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bedroom2', to='walkthroughreport.walkthroughreport')),
            ],
        ),
        migrations.CreateModel(
            name='Bedroom10',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('walkthrough_report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bedroom10', to='walkthroughreport.walkthroughreport')),
            ],
        ),
        migrations.CreateModel(
            name='Bedroom1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('walkthrough_report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bedroom1', to='walkthroughreport.walkthroughreport')),
            ],
        ),
        migrations.CreateModel(
            name='Bathroom9',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('walkthrough_report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bathroom9', to='walkthroughreport.walkthroughreport')),
            ],
        ),
        migrations.CreateModel(
            name='Bathroom8',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('walkthrough_report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bathroom8', to='walkthroughreport.walkthroughreport')),
            ],
        ),
        migrations.CreateModel(
            name='Bathroom7',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('walkthrough_report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bathroom7', to='walkthroughreport.walkthroughreport')),
            ],
        ),
        migrations.CreateModel(
            name='Bathroom6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('walkthrough_report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bathroom6', to='walkthroughreport.walkthroughreport')),
            ],
        ),
        migrations.CreateModel(
            name='Bathroom5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('walkthrough_report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bathroom5', to='walkthroughreport.walkthroughreport')),
            ],
        ),
        migrations.CreateModel(
            name='Bathroom4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('walkthrough_report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bathroom4', to='walkthroughreport.walkthroughreport')),
            ],
        ),
        migrations.CreateModel(
            name='Bathroom3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('walkthrough_report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bathroom3', to='walkthroughreport.walkthroughreport')),
            ],
        ),
        migrations.CreateModel(
            name='Bathroom2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('walkthrough_report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bathroom2', to='walkthroughreport.walkthroughreport')),
            ],
        ),
        migrations.CreateModel(
            name='Bathroom12',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('walkthrough_report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bathroom12', to='walkthroughreport.walkthroughreport')),
            ],
        ),
        migrations.CreateModel(
            name='Bathroom11',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('walkthrough_report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bathroom11', to='walkthroughreport.walkthroughreport')),
            ],
        ),
        migrations.CreateModel(
            name='Bathroom10',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('walkthrough_report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bathroom10', to='walkthroughreport.walkthroughreport')),
            ],
        ),
        migrations.CreateModel(
            name='Bathroom1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('walkthrough_report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bathroom1', to='walkthroughreport.walkthroughreport')),
            ],
        ),
    ]
