# Generated by Django 5.1.7 on 2025-04-04 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walkthroughreport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='walkthroughreport',
            name='gii10_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='gii1_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='gii2_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='gii3_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='gii4_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='gii5_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='gii6_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='gii7_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='gii8_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='gii9_remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
