# Generated by Django 5.1.7 on 2025-07-26 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walkthroughreport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalitemsexterior',
            name='gie10_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='generalitemsexterior',
            name='gie10_calculation_note',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='generalitemsexterior',
            name='gie10_client_approval',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Denied', 'Denied')], default='Pending', max_length=10),
        ),
        migrations.AddField(
            model_name='generalitemsexterior',
            name='gie10_udpate_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Open', 'Open'), ('Completed', 'Completed'), ('Denied', 'Denied')], default='Open', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='generalitemsexterior',
            name='gie10_update_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generalitemsexterior',
            name='gie10_update_remarks',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='generalitemsexterior',
            name='gie11_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='generalitemsexterior',
            name='gie11_calculation_note',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='generalitemsexterior',
            name='gie11_client_approval',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Denied', 'Denied')], default='Pending', max_length=10),
        ),
        migrations.AddField(
            model_name='generalitemsexterior',
            name='gie11_udpate_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Open', 'Open'), ('Completed', 'Completed'), ('Denied', 'Denied')], default='Open', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='generalitemsexterior',
            name='gie11_update_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generalitemsexterior',
            name='gie11_update_remarks',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='generalitemsexterior',
            name='gie12_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='generalitemsexterior',
            name='gie12_calculation_note',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='generalitemsexterior',
            name='gie12_client_approval',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Denied', 'Denied')], default='Pending', max_length=10),
        ),
        migrations.AddField(
            model_name='generalitemsexterior',
            name='gie12_udpate_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Open', 'Open'), ('Completed', 'Completed'), ('Denied', 'Denied')], default='Open', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='generalitemsexterior',
            name='gie12_update_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generalitemsexterior',
            name='gie12_update_remarks',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='generalitemsexterior',
            name='gie13_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='generalitemsexterior',
            name='gie13_calculation_note',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='generalitemsexterior',
            name='gie13_client_approval',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Denied', 'Denied')], default='Pending', max_length=10),
        ),
        migrations.AddField(
            model_name='generalitemsexterior',
            name='gie13_udpate_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Open', 'Open'), ('Completed', 'Completed'), ('Denied', 'Denied')], default='Open', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='generalitemsexterior',
            name='gie13_update_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generalitemsexterior',
            name='gie13_update_remarks',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='generalitemsexterior',
            name='gie14_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='generalitemsexterior',
            name='gie14_calculation_note',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='generalitemsexterior',
            name='gie14_client_approval',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Denied', 'Denied')], default='Pending', max_length=10),
        ),
        migrations.AddField(
            model_name='generalitemsexterior',
            name='gie14_udpate_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Open', 'Open'), ('Completed', 'Completed'), ('Denied', 'Denied')], default='Open', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='generalitemsexterior',
            name='gie14_update_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generalitemsexterior',
            name='gie14_update_remarks',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='generalitemsexterior',
            name='gie15_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='generalitemsexterior',
            name='gie15_calculation_note',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='generalitemsexterior',
            name='gie15_client_approval',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Denied', 'Denied')], default='Pending', max_length=10),
        ),
        migrations.AddField(
            model_name='generalitemsexterior',
            name='gie15_udpate_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Open', 'Open'), ('Completed', 'Completed'), ('Denied', 'Denied')], default='Open', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='generalitemsexterior',
            name='gie15_update_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generalitemsexterior',
            name='gie15_update_remarks',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='generalitemsexterior',
            name='gie1_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='generalitemsexterior',
            name='gie1_calculation_note',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='generalitemsexterior',
            name='gie1_client_approval',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Denied', 'Denied')], default='Pending', max_length=10),
        ),
        migrations.AddField(
            model_name='generalitemsexterior',
            name='gie1_udpate_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Open', 'Open'), ('Completed', 'Completed'), ('Denied', 'Denied')], default='Open', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='generalitemsexterior',
            name='gie1_update_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generalitemsexterior',
            name='gie1_update_remarks',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='generalitemsexterior',
            name='gie2_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='generalitemsexterior',
            name='gie2_calculation_note',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='generalitemsexterior',
            name='gie2_client_approval',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Denied', 'Denied')], default='Pending', max_length=10),
        ),
        migrations.AddField(
            model_name='generalitemsexterior',
            name='gie2_udpate_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Open', 'Open'), ('Completed', 'Completed'), ('Denied', 'Denied')], default='Open', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='generalitemsexterior',
            name='gie2_update_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generalitemsexterior',
            name='gie2_update_remarks',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='generalitemsexterior',
            name='gie3_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='generalitemsexterior',
            name='gie3_calculation_note',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='generalitemsexterior',
            name='gie3_client_approval',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Denied', 'Denied')], default='Pending', max_length=10),
        ),
        migrations.AddField(
            model_name='generalitemsexterior',
            name='gie3_udpate_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Open', 'Open'), ('Completed', 'Completed'), ('Denied', 'Denied')], default='Open', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='generalitemsexterior',
            name='gie3_update_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generalitemsexterior',
            name='gie3_update_remarks',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='generalitemsexterior',
            name='gie4_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='generalitemsexterior',
            name='gie4_calculation_note',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='generalitemsexterior',
            name='gie4_client_approval',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Denied', 'Denied')], default='Pending', max_length=10),
        ),
        migrations.AddField(
            model_name='generalitemsexterior',
            name='gie4_udpate_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Open', 'Open'), ('Completed', 'Completed'), ('Denied', 'Denied')], default='Open', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='generalitemsexterior',
            name='gie4_update_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generalitemsexterior',
            name='gie4_update_remarks',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='generalitemsexterior',
            name='gie5_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='generalitemsexterior',
            name='gie5_calculation_note',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='generalitemsexterior',
            name='gie5_client_approval',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Denied', 'Denied')], default='Pending', max_length=10),
        ),
        migrations.AddField(
            model_name='generalitemsexterior',
            name='gie5_udpate_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Open', 'Open'), ('Completed', 'Completed'), ('Denied', 'Denied')], default='Open', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='generalitemsexterior',
            name='gie5_update_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generalitemsexterior',
            name='gie5_update_remarks',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='generalitemsexterior',
            name='gie6_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='generalitemsexterior',
            name='gie6_calculation_note',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='generalitemsexterior',
            name='gie6_client_approval',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Denied', 'Denied')], default='Pending', max_length=10),
        ),
        migrations.AddField(
            model_name='generalitemsexterior',
            name='gie6_udpate_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Open', 'Open'), ('Completed', 'Completed'), ('Denied', 'Denied')], default='Open', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='generalitemsexterior',
            name='gie6_update_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generalitemsexterior',
            name='gie6_update_remarks',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='generalitemsexterior',
            name='gie7_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='generalitemsexterior',
            name='gie7_calculation_note',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='generalitemsexterior',
            name='gie7_client_approval',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Denied', 'Denied')], default='Pending', max_length=10),
        ),
        migrations.AddField(
            model_name='generalitemsexterior',
            name='gie7_udpate_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Open', 'Open'), ('Completed', 'Completed'), ('Denied', 'Denied')], default='Open', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='generalitemsexterior',
            name='gie7_update_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generalitemsexterior',
            name='gie7_update_remarks',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='generalitemsexterior',
            name='gie8_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='generalitemsexterior',
            name='gie8_calculation_note',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='generalitemsexterior',
            name='gie8_client_approval',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Denied', 'Denied')], default='Pending', max_length=10),
        ),
        migrations.AddField(
            model_name='generalitemsexterior',
            name='gie8_udpate_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Open', 'Open'), ('Completed', 'Completed'), ('Denied', 'Denied')], default='Open', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='generalitemsexterior',
            name='gie8_update_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generalitemsexterior',
            name='gie8_update_remarks',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='generalitemsexterior',
            name='gie9_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='generalitemsexterior',
            name='gie9_calculation_note',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='generalitemsexterior',
            name='gie9_client_approval',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Denied', 'Denied')], default='Pending', max_length=10),
        ),
        migrations.AddField(
            model_name='generalitemsexterior',
            name='gie9_udpate_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Open', 'Open'), ('Completed', 'Completed'), ('Denied', 'Denied')], default='Open', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='generalitemsexterior',
            name='gie9_update_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generalitemsexterior',
            name='gie9_update_remarks',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
