# Generated by Django 5.1.7 on 2025-04-04 19:23

import walkthroughreport.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('walkthroughreport', '0002_walkthroughreport_gii10_remarks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='walkthroughreport',
            name='gii10',
        ),
        migrations.RemoveField(
            model_name='walkthroughreport',
            name='gii10_remarks',
        ),
        migrations.AlterField(
            model_name='walkthroughreport',
            name='gii1',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Visual Inspection: Interior of House'),
        ),
        migrations.AlterField(
            model_name='walkthroughreport',
            name='gii2',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Exterior Doors Codes'),
        ),
        migrations.AlterField(
            model_name='walkthroughreport',
            name='gii3',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Exterior Doors & Hardware'),
        ),
        migrations.AlterField(
            model_name='walkthroughreport',
            name='gii4',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Exterior Windows & Hardware'),
        ),
        migrations.AlterField(
            model_name='walkthroughreport',
            name='gii5',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Smoke Detectors'),
        ),
        migrations.AlterField(
            model_name='walkthroughreport',
            name='gii6',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='A/C Air Handling Unit #1'),
        ),
        migrations.AlterField(
            model_name='walkthroughreport',
            name='gii7',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='A/C Air Handling Unit #2'),
        ),
        migrations.AlterField(
            model_name='walkthroughreport',
            name='gii8',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='A/C Air Handling Unit #3'),
        ),
        migrations.AlterField(
            model_name='walkthroughreport',
            name='gii9',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='A/C Air Handling Unit #4'),
        ),
    ]
