# Generated by Django 5.1.7 on 2025-04-06 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walkthroughreport', '0003_remove_walkthroughreport_gii10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='walkthroughreport',
            name='cost',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
