# Generated by Django 5.1.7 on 2025-04-06 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walkthroughreport', '0004_walkthroughreport_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='walkthroughreport',
            name='client_approval',
            field=models.BooleanField(default=False),
        ),
    ]
