# Generated by Django 5.1.7 on 2025-04-06 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walkthroughreport', '0005_walkthroughreport_client_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walkthroughreport',
            name='gie1_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='walkthroughreport',
            name='gie2_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='walkthroughreport',
            name='gie3_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
