# Generated by Django 5.1.7 on 2025-04-06 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walkthroughreport', '0006_alter_walkthroughreport_gie1_remarks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='walkthroughreport',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
