# Generated by Django 5.1.7 on 2025-04-06 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walkthroughreport', '0007_walkthroughreport_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='walkthroughreport',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
