# Generated by Django 5.1.7 on 2025-04-06 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walkthroughreport', '0008_walkthroughreport_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='walkthroughreport',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Denied', 'Denied')], default='Pending', max_length=20),
        ),
    ]
