# Generated by Django 5.1.7 on 2025-04-06 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walkthroughreport', '0009_walkthroughreport_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='walkthroughreport',
            name='updatedate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
