# Generated by Django 5.1.7 on 2025-04-06 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walkthroughreport', '0010_walkthroughreport_updatedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walkthroughreport',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Open', 'Open'), ('Completed', 'Completed'), ('Denied', 'Denied')], default='Pending', max_length=20),
        ),
    ]
