# Generated by Django 5.1.7 on 2025-04-09 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walkthroughreport', '0011_alter_walkthroughreport_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walkthroughreport',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Open', 'Open'), ('Completed', 'Completed'), ('Denied', 'Denied')], default='Pending', max_length=20, null=True),
        ),
    ]
