# Generated by Django 5.1.7 on 2025-04-09 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walkthroughreport', '0012_alter_walkthroughreport_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walkthroughreport',
            name='gii1_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='walkthroughreport',
            name='gii2_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='walkthroughreport',
            name='gii3_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
