# Generated by Django 5.1.7 on 2025-04-14 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walkthroughreport', '0013_alter_walkthroughreport_gii1_remarks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='walkthroughreport',
            name='breakfast1_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='breakfast2_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='breakfast3_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='breakfast4_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='breakfast5_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='butlers10_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='butlers11_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='butlers12_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='butlers1_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='butlers2_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='butlers3_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='butlers4_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='butlers5_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='butlers6_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='butlers7_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='butlers8_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='butlers9_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='closets1_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='closets2_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='closets3_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='closets4_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='closets5_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='closets_upper1_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='closets_upper2_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='closets_upper3_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='closets_upper4_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='closets_upper5_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='entry1_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='entry2_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='entry3_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='entry4_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='garage1_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='garage2_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='garage3_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='garage4_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='garage5_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='garage6_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='garage7_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='garage8_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='garage9_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='greatroom1_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='greatroom2_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='greatroom3_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='greatroom4_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='greatroom5_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='kitchen10_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='kitchen11_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='kitchen12_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='kitchen1_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='kitchen2_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='kitchen3_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='kitchen4_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='kitchen5_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='kitchen6_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='kitchen7_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='kitchen8_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='kitchen9_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='laundry1_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='laundry2_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='laundry3_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='laundry4_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='laundry5_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='laundry6_remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
