# Generated by Django 5.1.7 on 2025-04-19 21:12

import walkthroughreport.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walkthroughreport', '0016_walkthroughreport_bathroom1_1_remarks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom5_1',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Sinks: Faucet leaking, drain acceptable, overall condition'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom5_1_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom5_2',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Cabinets / Tops: Visual Check of cabinets, countertops'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom5_2_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom5_3',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Shower: Faucet leaking, drain acceptable, overall condition'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom5_3_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom5_4',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Bath/Hot Tub: Faucet leaking, drain acceptable, overall condition'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom5_4_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom5_5',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Toilet: Tank refills properly, Handle operational'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom5_5_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom5_6',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Lights: Any burnt out requiring replacement?'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom5_6_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom5_7',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Flooring / Walls / Ceilings: Visual check of floors/walls/ceilings'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom5_7_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom5_8',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Doors: Hardware working properly'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom5_8_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='walkthroughreport',
            name='breakfast1_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='walkthroughreport',
            name='breakfast2_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='walkthroughreport',
            name='breakfast3_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='walkthroughreport',
            name='breakfast4_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='walkthroughreport',
            name='breakfast5_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='walkthroughreport',
            name='gym_1',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Aa Sinks: Faucet leaking, drain acceptable, overall condition'),
        ),
    ]
