# Generated by Django 5.1.7 on 2025-05-11 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walkthroughreport', '0018_walkthroughreport_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walkthroughreport',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Open', 'Open'), ('Completed', 'Completed'), ('Denied', 'Denied')], default='Open', max_length=20, null=True),
        ),
    ]
