# Generated by Django 5.1.7 on 2025-05-12 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walkthroughreport', '0019_alter_walkthroughreport_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='walkthroughreport',
            name='hallways_upper2_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
