# Generated by Django 5.1.7 on 2025-06-20 10:59

import walkthroughreport.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walkthroughreport', '0020_walkthroughreport_hallways_upper2_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='walkthroughreport',
            name='gii10',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='A/C Air Handling Unit #5'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='gii10_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='walkthroughreport',
            name='gie11',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Mail '),
        ),
    ]
