# Generated by Django 5.1.7 on 2025-06-20 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walkthroughreport', '0021_walkthroughreport_gii10_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walkthroughreport',
            name='gii10_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
