# Generated by Django 5.1.7 on 2025-06-20 14:06

import walkthroughreport.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walkthroughreport', '0022_alter_walkthroughreport_gii10_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom10_1',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Sinks: Faucet leaking, drain acceptable, overall condition'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom10_1_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom10_2',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Cabinets / Tops: Visual Check of cabinets, countertops'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom10_2_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom10_3',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Shower: Faucet leaking, drain acceptable, overall condition'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom10_3_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom10_4',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Bath/Hot Tub: Faucet leaking, drain acceptable, overall condition'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom10_4_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom10_5',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Toilet: Tank refills properly, Handle operational'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom10_5_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom10_6',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Lights: Any burnt out requiring replacement?'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom10_6_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom10_7',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Flooring / Walls / Ceilings: Visual check of floors/walls/ceilings'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom10_7_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom10_8',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Doors: Hardware working properly'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom10_8_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom11_1',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Sinks: Faucet leaking, drain acceptable, overall condition'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom11_1_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom11_2',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Cabinets / Tops: Visual Check of cabinets, countertops'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom11_2_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom11_3',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Shower: Faucet leaking, drain acceptable, overall condition'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom11_3_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom11_4',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Bath/Hot Tub: Faucet leaking, drain acceptable, overall condition'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom11_4_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom11_5',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Toilet: Tank refills properly, Handle operational'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom11_5_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom11_6',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Lights: Any burnt out requiring replacement?'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom11_6_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom11_7',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Flooring / Walls / Ceilings: Visual check of floors/walls/ceilings'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom11_7_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom11_8',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Doors: Hardware working properly'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom11_8_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom12_1',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Sinks: Faucet leaking, drain acceptable, overall condition'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom12_1_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom12_2',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Cabinets / Tops: Visual Check of cabinets, countertops'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom12_2_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom12_3',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Shower: Faucet leaking, drain acceptable, overall condition'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom12_3_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom12_4',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Bath/Hot Tub: Faucet leaking, drain acceptable, overall condition'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom12_4_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom12_5',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Toilet: Tank refills properly, Handle operational'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom12_5_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom12_6',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Lights: Any burnt out requiring replacement?'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom12_6_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom12_7',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Flooring / Walls / Ceilings: Visual check of floors/walls/ceilings'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom12_7_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom12_8',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Doors: Hardware working properly'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom12_8_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom6_1',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Sinks: Faucet leaking, drain acceptable, overall condition'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom6_1_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom6_2',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Cabinets / Tops: Visual Check of cabinets, countertops'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom6_2_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom6_3',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Shower: Faucet leaking, drain acceptable, overall condition'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom6_3_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom6_4',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Bath/Hot Tub: Faucet leaking, drain acceptable, overall condition'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom6_4_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom6_5',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Toilet: Tank refills properly, Handle operational'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom6_5_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom6_6',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Lights: Any burnt out requiring replacement?'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom6_6_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom6_7',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Flooring / Walls / Ceilings: Visual check of floors/walls/ceilings'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom6_7_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom6_8',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Doors: Hardware working properly'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom6_8_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom7_1',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Sinks: Faucet leaking, drain acceptable, overall condition'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom7_1_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom7_2',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Cabinets / Tops: Visual Check of cabinets, countertops'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom7_2_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom7_3',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Shower: Faucet leaking, drain acceptable, overall condition'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom7_3_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom7_4',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Bath/Hot Tub: Faucet leaking, drain acceptable, overall condition'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom7_4_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom7_5',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Toilet: Tank refills properly, Handle operational'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom7_5_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom7_6',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Lights: Any burnt out requiring replacement?'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom7_6_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom7_7',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Flooring / Walls / Ceilings: Visual check of floors/walls/ceilings'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom7_7_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom7_8',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Doors: Hardware working properly'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom7_8_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom8_1',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Sinks: Faucet leaking, drain acceptable, overall condition'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom8_1_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom8_2',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Cabinets / Tops: Visual Check of cabinets, countertops'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom8_2_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom8_3',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Shower: Faucet leaking, drain acceptable, overall condition'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom8_3_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom8_4',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Bath/Hot Tub: Faucet leaking, drain acceptable, overall condition'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom8_4_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom8_5',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Toilet: Tank refills properly, Handle operational'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom8_5_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom8_6',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Lights: Any burnt out requiring replacement?'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom8_6_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom8_7',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Flooring / Walls / Ceilings: Visual check of floors/walls/ceilings'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom8_7_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom8_8',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Doors: Hardware working properly'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom8_8_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom9_1',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Sinks: Faucet leaking, drain acceptable, overall condition'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom9_1_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom9_2',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Cabinets / Tops: Visual Check of cabinets, countertops'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom9_2_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom9_3',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Shower: Faucet leaking, drain acceptable, overall condition'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom9_3_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom9_4',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Bath/Hot Tub: Faucet leaking, drain acceptable, overall condition'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom9_4_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom9_5',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Toilet: Tank refills properly, Handle operational'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom9_5_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom9_6',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Lights: Any burnt out requiring replacement?'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom9_6_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom9_7',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Flooring / Walls / Ceilings: Visual check of floors/walls/ceilings'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom9_7_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom9_8',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Doors: Hardware working properly'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom9_8_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bedroom10_1',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Furniture: Note any damage'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bedroom10_1_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bedroom10_2',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Lights: Any burnt out requiring replacement?'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bedroom10_2_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bedroom10_3',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Flooring / Walls / Ceilings: Visual check of floors/walls/ceilings'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bedroom10_3_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bedroom10_4',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Doors: Hardware working properly'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bedroom10_4_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bedroom5_1',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Furniture: Note any damage'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bedroom5_1_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bedroom5_2',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Lights: Any burnt out requiring replacement?'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bedroom5_2_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bedroom5_3',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Flooring / Walls / Ceilings: Visual check of floors/walls/ceilings'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bedroom5_3_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bedroom5_4',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Doors: Hardware working properly'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bedroom5_4_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bedroom6_1',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Furniture: Note any damage'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bedroom6_1_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bedroom6_2',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Lights: Any burnt out requiring replacement?'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bedroom6_2_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bedroom6_3',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Flooring / Walls / Ceilings: Visual check of floors/walls/ceilings'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bedroom6_3_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bedroom6_4',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Doors: Hardware working properly'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bedroom6_4_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bedroom7_1',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Furniture: Note any damage'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bedroom7_1_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bedroom7_2',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Lights: Any burnt out requiring replacement?'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bedroom7_2_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bedroom7_3',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Flooring / Walls / Ceilings: Visual check of floors/walls/ceilings'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bedroom7_3_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bedroom7_4',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Doors: Hardware working properly'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bedroom7_4_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bedroom8_1',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Furniture: Note any damage'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bedroom8_1_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bedroom8_2',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Lights: Any burnt out requiring replacement?'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bedroom8_2_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bedroom8_3',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Flooring / Walls / Ceilings: Visual check of floors/walls/ceilings'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bedroom8_3_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bedroom8_4',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Doors: Hardware working properly'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bedroom8_4_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bedroom9_1',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Furniture: Note any damage'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bedroom9_1_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bedroom9_2',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Lights: Any burnt out requiring replacement?'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bedroom9_2_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bedroom9_3',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Flooring / Walls / Ceilings: Visual check of floors/walls/ceilings'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bedroom9_3_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bedroom9_4',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Doors: Hardware working properly'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bedroom9_4_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='walkthroughreport',
            name='butlers1',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Refrigerator: Make sure the fridge is running '),
        ),
        migrations.AlterField(
            model_name='walkthroughreport',
            name='butlers2',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Freezer: Make sure freezer is running '),
        ),
        migrations.AlterField(
            model_name='walkthroughreport',
            name='garage1',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Refrigerator: Make sure the fridge is running '),
        ),
        migrations.AlterField(
            model_name='walkthroughreport',
            name='garage2',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Freezer: Make sure freezer is running '),
        ),
        migrations.AlterField(
            model_name='walkthroughreport',
            name='kitchen2',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Freezer: Make sure freezer is running'),
        ),
    ]
