# Generated by Django 5.1.7 on 2025-06-20 17:29

import walkthroughreport.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('walkthroughreport', '0023_walkthroughreport_bathroom10_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walkthroughreport',
            name='gym_1',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='All Sinks: Faucet leaking, drain acceptable, overall condition'),
        ),
    ]
