# Generated by Django 5.1.7 on 2025-06-22 19:51

import walkthroughreport.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walkthroughreport', '0024_alter_walkthroughreport_gym_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom10_10',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Window Treatment'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom10_10_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom10_9',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Windows'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom10_9_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom11_10',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Window Treatment'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom11_10_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom11_9',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Windows'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom11_9_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom12_10',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Window Treatment'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom12_10_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom12_9',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Windows'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom12_9_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom1_10',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Window Treatment'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom1_10_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom1_9',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Windows'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom1_9_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom2_10',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Window Treatment'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom2_10_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom2_9',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Windows'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom2_9_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom3_10',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Window Treatment'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom3_10_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom3_9',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Windows'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom3_9_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom4_10',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Window Treatment'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom4_10_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom4_9',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Windows'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom4_9_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom5_10',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Window Treatment'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom5_10_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom5_9',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Windows'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom5_9_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom6_10',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Window Treatment'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom6_10_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom6_9',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Windows'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom6_9_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom7_10',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Window Treatment'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom7_10_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom7_9',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Windows'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom7_9_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom8_10',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Window Treatment'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom8_10_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom8_9',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Windows'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom8_9_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom9_10',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Window Treatment'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom9_10_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom9_9',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Windows'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bathroom9_9_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bedroom10_5',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Windows'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bedroom10_5_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bedroom10_6',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Window Treatment'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bedroom10_6_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bedroom1_5',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Windows'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bedroom1_5_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bedroom1_6',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Window Treatment'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bedroom1_6_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bedroom2_5',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Windows'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bedroom2_5_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bedroom2_6',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Window Treatment'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bedroom2_6_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bedroom3_5',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Windows'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bedroom3_5_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bedroom3_6',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Window Treatment'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bedroom3_6_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bedroom4_5',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Windows'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bedroom4_5_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bedroom4_6',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Window Treatment'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bedroom4_6_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bedroom5_5',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Windows'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bedroom5_5_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bedroom5_6',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Window Treatment'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bedroom5_6_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bedroom6_5',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Windows'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bedroom6_5_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bedroom6_6',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Window Treatment'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bedroom6_6_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bedroom7_5',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Windows'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bedroom7_5_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bedroom7_6',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Window Treatment'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bedroom7_6_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bedroom8_5',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Windows'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bedroom8_5_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bedroom8_6',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Window Treatment'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bedroom8_6_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bedroom9_5',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Windows'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bedroom9_5_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bedroom9_6',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Window Treatment'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='bedroom9_6_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='breakfast6',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Windows'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='breakfast6_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='breakfast7',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Window Treatment'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='breakfast7_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='butlers13',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Windows'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='butlers13_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='butlers14',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Window Treatment'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='butlers14_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='dining6',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Windows'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='dining6_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='dining7',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Window Treatment'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='dining7_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='entry5',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Windows'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='entry5_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='entry6',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Window Treatment'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='entry6_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='greatroom6',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Windows'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='greatroom6_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='greatroom7',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Window Treatment'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='greatroom7_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='guest_house_6',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Windows'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='guest_house_6_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='guest_house_7',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Window Treatment'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='guest_house_7_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='guest_house_bath_10',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Window Treatment'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='guest_house_bath_10_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='guest_house_bath_9',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Windows'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='guest_house_bath_9_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='gym_8',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Windows'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='gym_8_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='gym_9',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Window Treatment'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='gym_9_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='theatre_6',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Windows'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='theatre_6_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='theatre_7',
            field=walkthroughreport.models.CategoryCharField(blank=True, choices=[('N/A', 'N/A'), ('Compliant', 'Compliant'), ('Heads-Up', 'Heads-Up'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True, verbose_name='Window Treatment'),
        ),
        migrations.AddField(
            model_name='walkthroughreport',
            name='theatre_7_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
