# Generated by Django 5.1.7 on 2025-06-25 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walkthroughreport', '0026_alter_walkthroughreport_client_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='walkthroughreport',
            name='completation_denied_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='walkthroughreport',
            name='client_approval',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Denied', 'Denied')], default='Pending', max_length=10),
        ),
    ]
