# Generated by Django 5.1.7 on 2025-07-09 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walkthroughreport', '0027_walkthroughreport_completation_denied_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walkthroughreport',
            name='client_approval',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Denied', 'Denied')], default='Pending', max_length=10),
        ),
    ]
