# Generated by Django 5.1.7 on 2025-04-02 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_client_contact_email_client_contact_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='contact_email',
            new_name='contact1_email',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='contact_name',
            new_name='contact1_name',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='contact_phone',
            new_name='contact1_phone',
        ),
        migrations.AddField(
            model_name='client',
            name='contact1_preferred',
            field=models.CharField(blank=True, choices=[('email', 'Email'), ('phone', 'Phone')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='contact2_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='contact2_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='contact2_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='contact2_preferred',
            field=models.CharField(blank=True, choices=[('email', 'Email'), ('phone', 'Phone')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='contact3_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='contact3_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='contact3_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='contact3_preferred',
            field=models.CharField(blank=True, choices=[('email', 'Email'), ('phone', 'Phone')], max_length=10, null=True),
        ),
    ]
