# Generated by Django 5.1.7 on 2025-04-02 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_rename_contact_email_client_contact1_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('service', models.CharField(choices=[('Appliance Repair', 'Appliance Repair'), ('Artificial Turf', 'Artificial Turf'), ('AV', 'AV'), ('Car Detailer', 'Car Detailer'), ('Carpet Cleaning', 'Carpet Cleaning'), ('Caterer / Chef', 'Caterer / Chef'), ('Countertops', 'Countertops')], max_length=50)),
            ],
        ),
    ]
