# Generated by Django 5.1.7 on 2025-04-05 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='service',
            field=models.CharField(blank=True, choices=[('Appliance Repair', 'Appliance Repair'), ('Artificial Turf', 'Artificial Turf'), ('AV', 'AV'), ('Car Detailer', 'Car Detailer'), ('Carpet Cleaning', 'Carpet Cleaning'), ('Caterer / Chef', 'Caterer / Chef'), ('Countertops', 'Countertops')], max_length=50, null=True),
        ),
    ]
