# Generated by Django 5.1.7 on 2025-04-14 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_vendor_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='contact1_preferred',
            field=models.CharField(blank=True, choices=[('email', 'Email'), ('phone', 'Phone'), ('text', 'text')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='contact2_preferred',
            field=models.CharField(blank=True, choices=[('email', 'Email'), ('phone', 'Phone'), ('text', 'text')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='contact3_preferred',
            field=models.CharField(blank=True, choices=[('email', 'Email'), ('phone', 'Phone'), ('text', 'text')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='preferred_contact_method',
            field=models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('text', 'text')], default='email', max_length=10),
        ),
        migrations.AlterField(
            model_name='clientmanagers',
            name='preferred_contact_method',
            field=models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('text', 'text')], default='email', max_length=10),
        ),
    ]
