# Generated by Django 5.1.7 on 2025-04-14 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_client_contact1_preferred_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='service',
            field=models.TextField(blank=True, null=True),
        ),
    ]
