# Generated by Django 5.1.7 on 2025-04-22 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_alter_vendor_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='contact1_last_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
