# Generated by Django 5.1.7 on 2025-04-22 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_client_contact1_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='contact2_last_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='contact3_last_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
