# Generated by Django 5.1.7 on 2025-04-23 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_client_contact2_last_name_client_contact3_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
