# Generated by Django 5.1.7 on 2025-04-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_alter_vendor_email_alter_vendor_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='contact4_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='contact4_last_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='contact4_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='contact4_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='contact4_preferred',
            field=models.CharField(blank=True, choices=[('email', 'Email'), ('phone', 'Phone'), ('text', 'text')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='contact5_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='contact5_last_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='contact5_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='contact5_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='contact5_preferred',
            field=models.CharField(blank=True, choices=[('email', 'Email'), ('phone', 'Phone'), ('text', 'text')], max_length=10, null=True),
        ),
    ]
