# Generated by Django 5.1.7 on 2025-04-26 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_client_contact4_email_client_contact4_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientmanagers',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
