# Generated by Django 5.1.7 on 2025-04-29 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_vendorservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='contact1_office_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='contact2_office_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='contact3_office_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='contact4_office_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='contact5_office_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
