# Generated by Django 5.1.7 on 2025-04-29 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_client_contact1_office_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='contact1_buisness_adress',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='contact2_buisness_adress',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='contact3_buisness_adress',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='contact4_buisness_adress',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='contact5_buisness_adress',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
