# Generated by Django 5.1.7 on 2025-05-01 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_client_contact1_buisness_adress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='contact1_priority',
            field=models.CharField(blank=True, choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('tertiary', 'Tertiary')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='contact2_priority',
            field=models.CharField(blank=True, choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('tertiary', 'Tertiary')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='contact3_priority',
            field=models.CharField(blank=True, choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('tertiary', 'Tertiary')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='contact4_priority',
            field=models.CharField(blank=True, choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('tertiary', 'Tertiary')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='contact5_priority',
            field=models.CharField(blank=True, choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('tertiary', 'Tertiary')], max_length=10, null=True),
        ),
    ]
