# Generated by Django 5.1.7 on 2025-05-01 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_client_contact1_priority_client_contact2_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='buisness_adress',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='office_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
