# Generated by Django 5.1.7 on 2025-05-01 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_client_buisness_adress_client_office_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientmanagers',
            name='business_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientmanagers',
            name='office_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
