# Generated by Django 5.1.7 on 2025-05-08 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_clientmanagers_business_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='buisness_adress',
        ),
        migrations.AddField(
            model_name='client',
            name='business_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
