# Generated by Django 5.1.7 on 2025-07-30 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0023_alter_client_password_alter_client_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='username',
        ),
        migrations.AddField(
            model_name='vendor',
            name='apt_suite',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='name',
            field=models.CharField(default=5, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='street',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
