# Generated by Django 5.1.7 on 2025-07-30 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0024_remove_vendor_username_vendor_apt_suite_vendor_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('cell', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='mainapp.vendor')),
            ],
        ),
    ]
