# Generated by Django 5.1.7 on 2025-09-07 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0026_rename_name_vendor_first_name_vendor_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='apt_suite',
            new_name='suite',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='first_name',
            new_name='website',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='address',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='last_name',
        ),
    ]
