# Generated by Django 5.1.7 on 2025-09-07 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0027_rename_apt_suite_vendor_suite_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=255)),
            ],
        ),
    ]
