# Generated by Django 5.1.7 on 2025-09-07 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0028_vendorservices'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VendorServices',
        ),
    ]
